#!/usr/bin/env bash

# Open the debug info
yabai -m config debug_output on

# ====== Tiling settings =======================

# Default bsp

yabai -m config layout  bsp                     

# Override default layout for space 2 only
yabai -m config --space 2 layout  float

# New window spawn to the left of vertical, or top if horizontal split.
# yabai -m config window_placement first_child

# New window spawn to the right of vertical, or bottom if horizontal split.
yabai -m config window_placement second_child

# Set all padding and gaps to 20pt (default 0)
yabai -m config top_padding                 20
yabai -m config bottom_padding              20
yabai -m config left_padding                20
yabai -m config right_padding               20
yabai -m config window_gap                  15

# Override gaps for space 2 only
yabai -m config --space 2 window_gap        0 

# ====== Split ratios =======================
yabai -m config auto_balance                off
yabai -m config split_ratio                 0.5


# ====== Mouse settings =======================

yabai -m config mouse_modifier              fn
yabai -m config mouse_follows_focus         off
yabai -m config focus_follows_mouse         off

# set modifier + left-click drag to move window
yabai -m config mouse_action1               move

# set modifier + right-click drag to resize window
yabai -m config mouse_action2               resize




# ====== Window modifications settings =======================

# floating windows are always on top (default: off)
yabai -m config window_topmost              on

# modify window shadows (on/off/float)
yabai -m config window_shadow               float


yabai -m config window_opacity              on
yabai -m config window_opacity_duration     0.0
yabai -m config active_window_opacity       1.0
yabai -m config normal_window_opacity       0.6






# ====== Border settings =======================

yabai -m config window_border               on
yabai -m config window_border_width         5
yabai -m config active_window_border_color  0xffd75f5f
yabai -m config insert_window_border_color  0xff505050
yabai -m config normal_window_border_color  0xff775759


# Refresh spaces widget on space change
# yabai -m signal --add event=space_changed action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-spaces-jsx\"'"
# Refresh spaces widget on display focus change
# yabai -m signal --add event=display_changed action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-spaces-jsx\"'"
# Refresh process widget on space change
# yabai -m signal --add event=space_changed action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-process-jsx\"'"

# Refresh process widget on when focused application changes
# yabai -m signal --add event=window_focused action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-process-jsx\"'"
# Refresh spaces widget on when focused application changes
# yabai -m signal --add event=window_focused action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-spaces-jsx\"'"

# Refresh process widget on when focused application changes
# yabai -m signal --add event=application_front_switched action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-process-jsx\"'"
# Refresh spaces widget on when focused application changes
# yabai -m signal --add event=application_front_switched action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-spaces-jsx\"'"

# Refresh process widget on when an application window is closed
# yabai -m signal --add event=window_destroyed action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-process-jsx\"'"
# Refresh spaces widget on when an application window is closed
# yabai -m signal --add event=window_destroyed action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-spaces-jsx\"'"

# Refresh process widget when current window title changes
# yabai -m signal --add event=window_title_changed action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-process-jsx\"'"
# echo "yabai configuration loaded ..."

