#!/usr/bin/env bash

###########################################################################################
###########################################################################################
###########################################################################################

# Message passing interface
# command formart: yabai --message <category> <command>

###########################################################################################
###########################################################################################
###########################################################################################


# Open kitty
# alt - return : "${HOME}"/.config/yabai/scripts/open_kitty.sh
# alt - return : "${HOME}"/.config/yabai/scripts/open_alacritty.sh
# alt - return : "${HOME}"/.config/yabai/scripts/open_iterm2.sh


# Show system statistics (Now use Uebersicht)

# ctrl + lalt - 1 : "${HOME}"/.config/yabai/scripts/show_cpu.sh
# ctrl + lalt - 2 : "${HOME}"/.config/yabai/scripts/show_mem.sh
# ctrl + lalt - 3 : "${HOME}"/.config/yabai/scripts/show_bat.sh
# ctrl + lalt - 4 : "${HOME}"/.config/yabai/scripts/show_disk.sh
# ctrl + lalt - 5 : "${HOME}"/.config/yabai/scripts/show_song.sh

###########################################################################################
# ============================================== Focus display(monitor) ===================
###########################################################################################

# Focus display with arrangement index
ctrl + shift + lalt - 1 : yabai -m display --focus 1
ctrl + shift + lalt - 2 : yabai -m display --focus 2

# Focus previous display(monitor) by arrangement index
ctrl + shift + lalt - p : yabai -m display --focus prev
# Focus next display(monitor) by arrangement index
ctrl + shift + lalt - n : yabai -m display --focus next

# Move window between display
#
ctrl + alt - p : yabai -m window --display 1 && yabai -m display --focus 1
ctrl + alt - n : yabai -m window --display 2 && yabai -m display --focus 2
#ctrl + alt - 3 : yabai -m window --display 3 && yabai -m display --focus 3


# ==================================== Switch window focus commands =========================
#
# Switch focus window
alt - h : yabai -m window --focus west
alt - k : yabai -m window --focus north
alt - j : yabai -m window --focus south
alt - l : yabai -m window --focus east


# Swtich windows
shift + alt - h : yabai -m window --warp west
shift + alt - j : yabai -m window --warp south
shift + alt - k : yabai -m window --warp north
shift + alt - l : yabai -m window --warp east


# ============================================ Resize window =================================

lctrl + alt - h :  yabai -m window --resize left:-20:0 ;    yabai -m window --resize right:-20:0
lctrl + alt - j :  yabai -m window --resize bottom:0:20 ;   yabai -m window --resize top:0:20
lctrl + alt - k :  yabai -m window --resize top:0:-20 ;     yabai -m window --resize bottom:0:-20
lctrl + alt - l :  yabai -m window --resize right:20:0 ;    yabai -m window --resize left:20:0


# ====== space  commands =========================

# Focus space

#ctrl + shift - j  : yabar -m space --focus prev
#ctrl + shift - k  : yabar -m space --focus next
#
#ctrl + shift + lalt - 1  : yabar -m space --focus 1
#ctrl + shift + lalt - 2  : yabar -m space --focus 2
#ctrl + shift + lalt - 3  : yabar -m space --focus 3

# Move focus container(window) to workspace(keep focus)

shift + alt - m : yabai -m window --space last && yabai -m space --focus last
shift + alt - p : yabai -m window --space prev && yabai -m space --focus prev
shift + alt - n : yabai -m window --space next && yabai -m space --focus next

shift + alt - 1 : yabai -m window --space 1 && yabai -m space --focus 1
shift + alt - 2 : yabai -m window --space 2 && yabai -m space --focus 2
shift + alt - 3 : yabai -m window --space 3 && yabai -m space --focus 3
shift + alt - 4 : yabai -m window --space 4 && yabai -m space --focus 4
shift + alt - 5 : yabai -m window --space 5 && yabai -m space --focus 5
shift + alt - 6 : yabai -m window --space 6 && yabai -m space --focus 6



# Create and destory spaces 


ctrl + alt - c : yabai -m space --create
ctrl + alt - d : yabai -m space --destroy




# Equalize size of windows
lctrl + alt - 0 : yabai -m space --balance

# Enable / Disable gaps in current workspace
lctrl + alt - g : yabai -m space --toggle padding; yabai -m space --toggle gap

# ========================= Rotate windows clockwise and anticlockwise =============================
alt - r         : yabai -m space --rotate 90
shift + alt - r : yabai -m space --rotate 270

# ==================================== Flip on X and Y Axis ========================================
alt - x : yabai -m space --mirror x-axis
alt - y : yabai -m space --mirror y-axis

# Set insertion point for focused container
#shift + lctrl + alt - h : yabai -m window --insert west
#shift + lctrl + alt - j : yabai -m window --insert south
#shift + lctrl + alt - k : yabai -m window --insert north
#shift + lctrl + alt - l : yabai -m window --insert east

# ============================= Window move setting ===================
#

# Float / Unfloat window
shift + alt - space : yabai -m window --toggle float

# Float and center window
shift + alt - c : yabai -m window --toggle float; yabai -m window --grid 4:4:1:1:2:2

# Make window native fullscreen
alt - f         : yabai -m window --toggle zoom-fullscreen
shift + alt - f : yabai -m window --toggle native-fullscreen


# Move  window
ctrl + alt - h: yabai -m window rel:-50:0
ctrl + alt - l: yabai -m window rel:50:0
ctrl + alt - j: yabai -m window rel:0:-50
ctrl + alt - k: yabai -m window rel:0:50

# resize float window


# Restart Yabai
shift + lctrl + alt - r :
    /usr/bin/env osascript <<< \
        "display notification \"Restarting Yabai\" with title \"Yabai\""; \
    launchctl kickstart -k "gui/${UID}/homebrew.mxcl.yabai"

